image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 4.0.0-debian-12-r10

extraEnvVars:
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"

extraConfigYaml:
  message.max.bytes: 524288000 # 500 MB
  replica.fetch.max.bytes: 524288000 # 500 MB para réplicas
  max.request.size: 524288000 # 500 MB para el tamaño máximo de la solicitud
  auto.create.topics.enable: true
  topic.creation.enable: true
  topic.creation.default.replication.factor: 3
  topic.creation.default.partitions: 10

listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""
  external:
    containerPort: 9095
    protocol: PLAINTEXT
    name: EXTERNAL
    sslClientAuth: ""

podDisruptionBudget:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 80
  targetMemory: 80