global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'selling-system--microservices'
    eureka_sd_configs:
      - server: 'http://PC-David:8761/eureka'
    relabel_configs:
      
      - source_labels: [__meta_eureka_app_name]
        action: replace
        target_label: service

      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      - source_labels: [__meta_eureka_app_instance_id]
        action: replace
        target_label: instance