version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: "unless-stopped"
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - redis-network

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge
